#!/bin/bash
set -euo pipefail

# Nextgram TrollStore build helper
# Target: Nextgram-iOS source supplied by the user.
# Builds the main app + six iOS extensions using the repository's disposable
# fake-signing certificate/profile machinery, then removes embedded signatures
# and provisioning profiles from the final IPA for TrollStore installation.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="${NEXTGRAM_REPO:-$(cd "$ROOT/.." && pwd)}"
BUILD_INPUT="$REPO/build-input"
CACHE_DIR="${NEXTGRAM_BAZEL_CACHE:-$HOME/telegram-bazel-cache}"
BUNDLE_ID="${NEXTGRAM_BUNDLE_ID:-jp.foxtea.nextgram}"
TEAM_ID="${NEXTGRAM_TEAM_ID:-C67CF9S4VU}"
BUILD_NUMBER="${NEXTGRAM_BUILD_NUMBER:-$(git -C "$REPO" rev-list --count HEAD 2>/dev/null || echo 1)}"
OUT_DIR="${NEXTGRAM_OUT:-$REPO/build/trollstore}"

: "${TELEGRAM_API_ID:?Set TELEGRAM_API_ID to your Telegram API ID}"
: "${TELEGRAM_API_HASH:?Set TELEGRAM_API_HASH to your Telegram API hash}"

command -v python3 >/dev/null || { echo "python3 is required"; exit 1; }
command -v openssl >/dev/null || { echo "openssl is required"; exit 1; }
command -v security >/dev/null || { echo "macOS security is required"; exit 1; }
command -v plutil >/dev/null || { echo "macOS plutil is required"; exit 1; }

cd "$REPO"

if [[ ! -f "build-system/Make/Make.py" || ! -f "Telegram/BUILD" ]]; then
  echo "ERROR: NEXTGRAM_REPO does not look like the Nextgram source root:"
  echo "  $REPO"
  exit 1
fi

echo "==> Checking submodules"
git submodule update --init --recursive

echo "==> Selecting Xcode"
if [[ -n "${DEVELOPER_DIR:-}" ]]; then
  export DEVELOPER_DIR
else
  XC="$(ls -d /Applications/Xcode_26*.app /Applications/Xcode.app 2>/dev/null | sort -V | tail -1 || true)"
  [[ -n "$XC" ]] || { echo "No Xcode installation found"; exit 1; }
  export DEVELOPER_DIR="$XC/Contents/Developer"
fi
xcodebuild -version
xcode-select -p

echo "==> Optional Metal toolchain download"
xcodebuild -downloadComponent MetalToolchain || true

echo "==> Verifying source bundle ID"
if grep -q 'BUNDLE_ID.*jp\.foxtea\.nextgram' .github/workflows/build.yml; then
  echo "    Nextgram bundle ID: $BUNDLE_ID"
else
  echo "WARNING: source workflow does not contain the expected Nextgram bundle ID."
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

# IMPORTANT: no disableExtensions and no disableProvisioningProfiles.
cat > "$REPO/local.bazelrc" <<EOF
# Generated by build-nextgram-trollstore.sh
# Extensions MUST remain enabled for the TrollStore build.
build --repo_env=DEVELOPER_DIR=$DEVELOPER_DIR
build --action_env=DEVELOPER_DIR=$DEVELOPER_DIR
build --host_action_env=DEVELOPER_DIR=$DEVELOPER_DIR
build --features=no_include_scanning
build --host_features=no_include_scanning
build --copt=-Wno-deprecated-declarations
build --@build_bazel_rules_swift//swift:copt=-no-warnings-as-errors
EOF

mkdir -p "$BUILD_INPUT/nextgram-trollstore-codesigning/certs"
mkdir -p "$BUILD_INPUT/nextgram-trollstore-codesigning/profiles"

cp -f build-system/fake-codesigning/certs/Public.cer \
  "$BUILD_INPUT/nextgram-trollstore-codesigning/certs/"
cp -f build-system/fake-codesigning/certs/SelfSigned.p12 \
  "$BUILD_INPUT/nextgram-trollstore-codesigning/certs/"

echo "==> Creating Nextgram configuration"
cat > "$BUILD_INPUT/nextgram-trollstore.json" <<JSON
{
  "bundle_id": "$BUNDLE_ID",
  "api_id": "$TELEGRAM_API_ID",
  "api_hash": "$TELEGRAM_API_HASH",
  "team_id": "$TEAM_ID",
  "app_center_id": "0",
  "is_internal_build": "true",
  "is_appstore_build": "false",
  "appstore_id": "0",
  "app_specific_url_scheme": "nextgram",
  "premium_iap_product_id": "",
  "enable_siri": false,
  "enable_icloud": false
}
JSON

echo "==> Generating all six extension provisioning profiles"
# The repository's fake profiles are signed profiles for the Nagram bundle ID.
# We rewrite the profile payload, replacing the Nagram bundle/app-group IDs with
# Nextgram IDs, then sign the modified payload with the repository's disposable
# certificate. The build system only needs to parse the resulting profiles and
# use their entitlements; the final IPA has the profiles removed before packaging.

PROFILE_SRC="build-system/fake-codesigning/profiles"
PROFILE_DST="$BUILD_INPUT/nextgram-trollstore-codesigning/profiles"
PROFILE_PLIST="$OUT_DIR/profile.plist"
SIGNING_PEM="$OUT_DIR/fake-signing.pem"

openssl pkcs12 -in build-system/fake-codesigning/certs/SelfSigned.p12 \
  -passin pass: -nodes -legacy -out "$SIGNING_PEM"

python3 "$ROOT/rewrite_profiles.py" \
  "$PROFILE_SRC" "$PROFILE_DST" "$BUNDLE_ID" "$TEAM_ID" "$PROFILE_PLIST" "$SIGNING_PEM"

rm -f "$PROFILE_PLIST" "$SIGNING_PEM"

EXPECTED_PROFILES=(
  Telegram.mobileprovision
  Share.mobileprovision
  NotificationContent.mobileprovision
  NotificationService.mobileprovision
  Intents.mobileprovision
  Widget.mobileprovision
  BroadcastUpload.mobileprovision
)

for p in "${EXPECTED_PROFILES[@]}"; do
  test -f "$PROFILE_DST/$p" || { echo "ERROR: missing generated profile $p"; exit 1; }
done

echo "==> Building Nextgram with extensions ENABLED"
rm -rf "$REPO/bazel-bin/Telegram/Telegram.ipa"

python3 build-system/Make/Make.py --overrideXcodeVersion \
  --cacheDir "$CACHE_DIR" \
  build \
  --configurationPath "$BUILD_INPUT/nextgram-trollstore.json" \
  --codesigningInformationPath "$BUILD_INPUT/nextgram-trollstore-codesigning" \
  --buildNumber "$BUILD_NUMBER" \
  --configuration release_arm64

IPA="$REPO/bazel-bin/Telegram/Telegram.ipa"
test -f "$IPA" || { echo "ERROR: build did not produce $IPA"; exit 1; }

echo "==> Verifying extension-enabled IPA"
rm -rf "$OUT_DIR/package"
mkdir -p "$OUT_DIR/package"
ditto -x -k "$IPA" "$OUT_DIR/package"

APP_PATH="$(find "$OUT_DIR/package/Payload" -maxdepth 1 -type d -name '*.app' -print -quit)"
test -n "$APP_PATH" || { echo "ERROR: no .app found"; exit 1; }

ACTUAL_BUNDLE_ID="$(plutil -extract CFBundleIdentifier raw "$APP_PATH/Info.plist")"
[[ "$ACTUAL_BUNDLE_ID" == "$BUNDLE_ID" ]] || {
  echo "ERROR: expected bundle ID $BUNDLE_ID, got $ACTUAL_BUNDLE_ID"
  exit 1
}

echo "Embedded extensions:"
find "$APP_PATH/PlugIns" -maxdepth 1 -type d -name '*.appex' -print 2>/dev/null || true

for ext in Share NotificationContent NotificationService Intents Widget BroadcastUpload; do
  path="$APP_PATH/PlugIns/$ext.appex"
  test -d "$path" || { echo "ERROR: missing $ext.appex"; exit 1; }
done

echo "==> Checking extension bundle identifiers"
python3 "$ROOT/verify_ipa.py" "$APP_PATH" "$BUNDLE_ID"

echo "==> Removing temporary code signatures and provisioning profiles"
find "$APP_PATH" -type d -name _CodeSignature -prune -exec rm -rf {} +
find "$APP_PATH" -name embedded.mobileprovision -delete

# Also remove any nested signature directories left inside frameworks/bundles.
find "$APP_PATH" -type d -name _CodeSignature -prune -exec rm -rf {} +

echo "==> Creating TrollStore IPA"
rm -f "$OUT_DIR/Nextgram-TrollStore.ipa"
(
  cd "$OUT_DIR/package"
  /usr/bin/zip -qry "$OUT_DIR/Nextgram-TrollStore.ipa" Payload
)

echo "==> Final verification"
python3 "$ROOT/verify_ipa.py" "$OUT_DIR/Nextgram-TrollStore.ipa" "$BUNDLE_ID"

echo
echo "SUCCESS"
echo "IPA: $OUT_DIR/Nextgram-TrollStore.ipa"
echo
echo "The IPA contains the main app plus:"
echo "  - Share.appex"
echo "  - NotificationContent.appex"
echo "  - NotificationService.appex"
echo "  - Intents.appex"
echo "  - Widget.appex"
echo "  - BroadcastUpload.appex"
echo
echo "Install the resulting IPA with TrollStore on your iOS 17.0 device."
